require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RedeemsController do

  # This should return the minimal set of attributes required to create a valid
  # Redeem. As you add validations to Redeem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "transaction_code" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RedeemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all redeems as @redeems" do
      redeem = Redeem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:redeems).should eq([redeem])
    end
  end

  describe "GET show" do
    it "assigns the requested redeem as @redeem" do
      redeem = Redeem.create! valid_attributes
      get :show, {:id => redeem.to_param}, valid_session
      assigns(:redeem).should eq(redeem)
    end
  end

  describe "GET new" do
    it "assigns a new redeem as @redeem" do
      get :new, {}, valid_session
      assigns(:redeem).should be_a_new(Redeem)
    end
  end

  describe "GET edit" do
    it "assigns the requested redeem as @redeem" do
      redeem = Redeem.create! valid_attributes
      get :edit, {:id => redeem.to_param}, valid_session
      assigns(:redeem).should eq(redeem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Redeem" do
        expect {
          post :create, {:redeem => valid_attributes}, valid_session
        }.to change(Redeem, :count).by(1)
      end

      it "assigns a newly created redeem as @redeem" do
        post :create, {:redeem => valid_attributes}, valid_session
        assigns(:redeem).should be_a(Redeem)
        assigns(:redeem).should be_persisted
      end

      it "redirects to the created redeem" do
        post :create, {:redeem => valid_attributes}, valid_session
        response.should redirect_to(Redeem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved redeem as @redeem" do
        # Trigger the behavior that occurs when invalid params are submitted
        Redeem.any_instance.stub(:save).and_return(false)
        post :create, {:redeem => { "transaction_code" => "invalid value" }}, valid_session
        assigns(:redeem).should be_a_new(Redeem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Redeem.any_instance.stub(:save).and_return(false)
        post :create, {:redeem => { "transaction_code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested redeem" do
        redeem = Redeem.create! valid_attributes
        # Assuming there are no other redeems in the database, this
        # specifies that the Redeem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Redeem.any_instance.should_receive(:update_attributes).with({ "transaction_code" => "MyString" })
        put :update, {:id => redeem.to_param, :redeem => { "transaction_code" => "MyString" }}, valid_session
      end

      it "assigns the requested redeem as @redeem" do
        redeem = Redeem.create! valid_attributes
        put :update, {:id => redeem.to_param, :redeem => valid_attributes}, valid_session
        assigns(:redeem).should eq(redeem)
      end

      it "redirects to the redeem" do
        redeem = Redeem.create! valid_attributes
        put :update, {:id => redeem.to_param, :redeem => valid_attributes}, valid_session
        response.should redirect_to(redeem)
      end
    end

    describe "with invalid params" do
      it "assigns the redeem as @redeem" do
        redeem = Redeem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Redeem.any_instance.stub(:save).and_return(false)
        put :update, {:id => redeem.to_param, :redeem => { "transaction_code" => "invalid value" }}, valid_session
        assigns(:redeem).should eq(redeem)
      end

      it "re-renders the 'edit' template" do
        redeem = Redeem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Redeem.any_instance.stub(:save).and_return(false)
        put :update, {:id => redeem.to_param, :redeem => { "transaction_code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested redeem" do
      redeem = Redeem.create! valid_attributes
      expect {
        delete :destroy, {:id => redeem.to_param}, valid_session
      }.to change(Redeem, :count).by(-1)
    end

    it "redirects to the redeems list" do
      redeem = Redeem.create! valid_attributes
      delete :destroy, {:id => redeem.to_param}, valid_session
      response.should redirect_to(redeems_url)
    end
  end

end
